// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetModelDownloadLinks(arg1) {
  return window['go']['main']['App']['GetModelDownloadLinks'](arg1);
}

export function InstallModel(arg1, arg2) {
  return window['go']['main']['App']['InstallModel'](arg1, arg2);
}
