// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetModelDownloadLinks(arg1:string):Promise<main.GetLinkResponse>;

export function InstallModel(arg1:string,arg2:string):Promise<void>;
